### ISSUE TITLE
Loading `rflsgen` from RStudio crashes R session

### ISSUE THREAD

**Issue by CeresBarros** [dimitri-justeau/rflsgen#2]
Hi there,

I've been trying to use `rflsgen` from RStudio but when I try to load it, it crashes the R session. I've noticed that this doesn't happen when the package is loaded from an R terminal window, so presumably there's some issue with RStudio itself?

What I've tried:
- updating RStudio
- Resetting RStudio's  state (https://support.rstudio.com/hc/en-us/articles/200534577-Resetting-RStudio-Desktop-s-State)
- installing `rflsgen` from GitHub
- loading `rflsgen` dependencies first (i.e. `rJava`, `terra` and `jsonlite`) and only then `rflsgen` -- note that each of the dependencies loads fine.
- updating Java for Windows from [here](https://www.oracle.com/java/technologies/downloads/#jdk19-windows) and then setting env variable `$JAVA_HOME`  to point to the updated Java location (as shown [here](https://stackoverflow.com/questions/58580867/change-java-version-in-r-studio))

I'm out of ideas as to what may be the problem or the solution :/ and unfortunately I have to be able to use RStudio as I rely on it for project and package development/management a lot.

Thanks in advance for your help

**Comment by CeresBarros** [comment]
forgot to add my `sessionInfo`: 
```
> sessionInfo()
R version 4.2.0 (2022-04-22 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_Canada.utf8  LC_CTYPE=English_Canada.utf8    LC_MONETARY=English_Canada.utf8 LC_NUMERIC=C                   
[5] LC_TIME=English_Canada.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.2.0 tools_4.2.0   
```

**Comment by CeresBarros** [comment]
Oh, I think I've made some progress, the issue may be with `rJava` after all:
![image](https://user-images.githubusercontent.com/22214224/197282783-89ae4f0c-9dd8-4db7-9a1a-2af6f31b79d7.png)

and possible related to this: https://github.com/rstudio/rstudio/issues/11076

**Comment by CeresBarros** [comment]
I can confirm that updating R to R version 4.2.2 beta (2022-10-20 r83147 ucrt) solves this issue. Apologies for bothering you :)

**Comment by dimitri-justeau** [comment]
Hi ! No need to apology, you opened and solved the problem while I was sleeping (I'm on France) 🙂

Thank you for identifying this problem, it will be iseful if someone else faces the same issue !

Cheers,

Dimitri.
